spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

logging:
  level:
    root: INFO
    com.demo.jooq: DEBUG
    org.springframework.test: DEBUG
