spring:
  # 데이터베이스 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

# REST Docs 설정
spring.test.restdocs:
  uriScheme: http
  uriHost: localhost
  uriPort: 8080

# 로깅 레벨 설정
logging:
  level:
    root: INFO
    com.demo.jooq: DEBUG
    org.springframework.test: DEBUG
